### ISSUE TITLE
Error after pulling the new version

### ISSUE THREAD

**Issue by BabsDR** [EpiDiverse/dmr#3]
Hello guys, both Dario and me got this error with the new pipe version. I was just checking for him, the old version I had worked fine, and then I pulled the last version and got the error. Thanks in advance!

`nextflow run epidiverse/dmr --help`
N E X T F L O W  ~  version 19.09.0-edge
Launching `epidiverse/dmr` [mighty_linnaeus] - revision: 13c439d861 [master]
Script compilation error
- file : /homes/epi/barbara/.nextflow/assets/epidiverse/dmr/main.nf
- cause: Not a valid include definition -- it must specify the module path as a string @ line 209, column 9.
           include {check_test_data} from './lib/functions.nf' params(CpGPaths: params.CpGPaths, CHGPaths: params.CHGPaths, noCpG: params.noCpG, noCHG: params.noCHG)
           ^

Script compilation error
- file : /homes/epi/barbara/.nextflow/assets/epidiverse/dmr/main.nf
- cause: Not a valid include definition -- it must specify the module path as a string @ line 247, column 1.
   include {preprocessing;bedtools_unionbedg;metilene;distributions;heatmaps} from './lib/dmr.nf' params(params)
   ^

**Comment by nilaycan** [comment]
Hey Bárbara! 

The problem is due to the update of DSL2 syntax with the newest version of Nextlow. Please do the followings:

-create a conda env
-install the newest version of Nextflow (usual installation process will make you to install the newest version already)
-activate the env
-run the pipeline

It should solve it (and it worked according to your informing).

Thanks for noticing!
